### ISSUE TITLE
Parse output keys as keywords

### ISSUE THREAD

**Issue by AxelRHD** [gerritjvv/pjson#37]
As the title says: is it possible to return parsed data with keywords instead of strings?

Thank you.

**Comment by gerritjvv** [comment]
Hi, I left this out due to the performance impact of Strings to keywords. 

Up till now, the use cases have been: "I really need speed" so using "mykey" instead of :mykey  was a minor in convenience.

You could always use: keywordize-keys

e.g: 
```
(require '[clojure.walk :refer [keywordize-keys]])
(keywordize-keys {"a" 1 "b" {"c" 2}})
;;>> {:a 1, :b {:c 2}}
```

If its a big show stopper for your use case though, plz tell me and I can send sometime on trying see if I can find a way to add it in without a performance hit on the existing non keywordize logic.

**Comment by AxelRHD** [comment]
Thank you for the quick answer. I hadn't that solution in my mind. It will do the job.

**Comment by niquola** [comment]
Hi, amazing performance!

In our platform have convention that keys are keywords.
keywordize-keys  kills performance make it 3times slower than cheshire.

**Comment by niquola** [comment]
If you hint me the right place to add this feature - I can work on it

**Comment by niquola** [comment]
So probably keywordize may speed up pjson as well

**Comment by gerritjvv** [comment]
Hi @niquola, I'll take a look, its been a while since I opened the pjson source code.
My initial reason for leaving out keywordize was to not add the extra performance over head. 

But its true that in most clojure projects people use keywords. It would be interesting to see how cheshire does the keyword reading.

Re the speedups, performance testing is a slippery slope. You might gain in one use case and completely loose in another. One option I can do is add a Function call that can be overwritten to every place I would use a string as a key. This would give any user the option to convert to keywords or not, and hopefully not interfere with the default call site (i.e default should be identity and the JVM should jit it out).

I'll take a look, it would be interesting.

**Comment by niquola** [comment]
Thank you!

**Comment by gerritjvv** [comment]
@niquola I had finally saw how to clearly implement this. See https://github.com/gerritjvv/pjson/tree/feature/keyword-support .

can you run your tests with `1.0.0-SNAPSHOT` see what the performance is for you?

use 
```
(binding [pjson.core/*key-fn* keyword]
  (read-str "{\"a\":1}"))
```

Some background on why the dynamic var and my thought process:

  * I can't add varargs to the protocol and read-str is a protocol method
  * Adding an argument key-fn to every signature in the read-str doesn't feel right from a design point.
  * The dynamic var allows existing code to just work and doesn't need signature changes or breaking changes
  * I'll add a helper method like read-str-keys soon.
